# Generated by Django 3.0.6 on 2020-07-12 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='list_unsat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='QuesType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Query_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quesion', models.CharField(max_length=400)),
                ('answer', models.TextField()),
                ('satisfied', models.IntegerField(default=0, verbose_name='satisfied')),
                ('unsatisfied', models.IntegerField(default=0, verbose_name='unsat')),
                ('viewed', models.IntegerField(default=0, verbose_name='viewed')),
                ('queType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.QuesType')),
            ],
        ),
    ]
