# Generated by Django 3.0.6 on 2020-07-13 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list_unsat',
            name='dbqid',
            field=models.IntegerField(default=0, verbose_name='dbqid'),
        ),
    ]
